Добавил 1 версию решения задачи 2-6
pyaiveoleg/BasicProgramming pull request #10
Opened 2019-09-24 19:22 UTC by pyaiveoleg

2019-10-08 11:22 UTC, jzuken requested changes

2019-10-08 11:22 UTC, jzuken commented on 2-6.c
> +        consistance[number%10]++;
пробелов не хватает

2019-10-08 11:22 UTC, jzuken commented on 2-6.c
> +    int consistance[quantityOfDigits];
это какое-то неудачное название, из него непонятно, что там лежит внутри

2019-10-08 11:22 UTC, jzuken commented on 2-6.c
> +    printf("This is parsed number: %d", parsedNumber);
Please, write down number N: 123120
This is parsed number: 110223

почему так?

2019-10-17 12:53 UTC, SpirinEgor requested changes

2019-10-17 12:53 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-6/2-6.c
> +void addNewDigit(int digit, unsigned long long *parsedNumber, int *quantityOfEachDigit)
По названию функции выглядит, что здесь добавляется всего одна цифра.

2019-10-17 12:53 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-6/2-6.c
> +void addNewDigit(int digit, unsigned long long *parsedNumber, int *quantityOfEachDigit)
Так же лучше сделать сигнатуру функции без передавания массива -- передаём число, добавляемую цифру и количество, а возвращаем новое число.

2019-11-18 16:51 UTC, SpirinEgor requested changes

2019-11-18 16:51 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-6/2-6.c
> +int main() {
И тут скобочка не там

2019-11-24 00:45 UTC, fefaleksey approved these changes
теперь ок

2019-11-24 12:13 UTC, merged