Задача 3-1
pyaiveoleg/BasicProgramming pull request #13
Opened 2019-10-08 18:07 UTC by pyaiveoleg

2019-10-22 10:54 UTC, jzuken requested changes

2019-10-22 10:54 UTC, jzuken commented on Semester_1/Homework_3/Task_3-1/3-1.c
> +        else if (array[root * 2] > array[root * 2 + 1])
эти индексы тут имеют особый смысл, стоит завести для них особые переменные

2019-10-22 10:54 UTC, jzuken commented on Semester_1/Homework_3/Task_3-1/3-1.c
> +        else if (array[root * 2] > array[root * 2 + 1])
эти индексы тут имеют особый смысл, стоит завести для них особые переменные

2019-11-20 12:32 UTC, SpirinEgor requested changes

2019-11-20 12:32 UTC, SpirinEgor commented on Semester_1/Homework_3/Task_3-1/main.c
> +int main() {
Эх, опять не там(

2019-11-20 12:32 UTC, SpirinEgor commented on Semester_1/Homework_3/Task_3-1/main.c
> +    int rightChild = root * 2 + 1;
А точно так?
Если у тебя 0-нумерация, а это так, потому что ты читаешь исходный массив в `array[0]`,
тогда `leftChild` корня: `0 * 2 = 0`, что немного бессмысленно

2019-11-23 19:57 UTC, fefaleksey approved these changes
Теперь ок

2019-11-23 20:13 UTC, merged