Задача 3-2
pyaiveoleg/BasicProgramming pull request #14
Opened 2019-10-08 18:08 UTC by pyaiveoleg

2019-10-22 10:56 UTC, jzuken requested changes

2019-10-22 10:56 UTC, jzuken commented on Semester_1/Homework_3/Task_3-2/3-2.c
> +        printf("Error. Cannot open file.\n");
было бы здорово ещё и тестовый файл выкладывать

2019-10-22 10:56 UTC, jzuken commented on Semester_1/Homework_3/Task_3-2/3-2.c
> +    if (input)
а лучше было бы инвертировать условие и сразу выйти. тогда не надо будет else писать

2019-11-20 12:34 UTC, SpirinEgor requested changes

2019-11-20 12:34 UTC, SpirinEgor commented on Semester_1/Homework_3/Task_3-2/main.c
> +int main() {
Ну что же такое,
Пройдись по всем пр и поправь...

2019-12-01 19:40 UTC, fefaleksey approved these changes
ok

2019-12-02 16:46 UTC, merged