Задача 4-2
pyaiveoleg/BasicProgramming pull request #17
Opened 2019-10-08 18:10 UTC by pyaiveoleg

2019-10-22 11:03 UTC, jzuken requested changes

2019-10-22 11:03 UTC, jzuken commented on Semester_1/Homework_4/Task_4-2/4-2.c
> +                output = fopen("output.txt", "w");
тебя не смущает, что оно пишет в один файл, а читает из другого? как с этим работать то?

2019-10-22 11:03 UTC, jzuken commented on Semester_1/Homework_4/Task_4-2/4-2.c
> +int searchByPhone(unsigned long long phones[], unsigned long long phone, int quantityOfNotes)
хочется модуль для работы с телефонной книжкой

2019-11-24 01:21 UTC, fefaleksey commented on Semester_1/Homework_4/Task_4-2/PhoneBook.c
> +}
В функцию передается копия указателя. Исходный указатель не изменится

2019-11-24 01:21 UTC, fefaleksey commented on Semester_1/Homework_4/Task_4-2/PhoneBook.c
> +}
А ещё PhoneBook расширять не надо))

2019-11-24 01:21 UTC, fefaleksey commented on Semester_1/Homework_4/Task_4-2/PhoneBook.c
> +    (phoneBook->size)++;
скобки не нужны

2019-11-24 01:21 UTC, fefaleksey commented on Semester_1/Homework_4/Task_4-2/PhoneBook.h
> +#define INC_4_2_PHONEBOOK_H
#pragma once

2019-11-24 01:21 UTC, fefaleksey commented on Semester_1/Homework_4/Task_4-2/main.c
> +        }
Это отдельная функция

2019-12-01 21:12 UTC, fefaleksey approved these changes
ok

2019-12-02 16:55 UTC, jzuken requested changes

2019-12-02 16:55 UTC, jzuken commented on Semester_1/Homework_4/Task_4-2/PhoneBook.c
> +        return false;
очень странное поведение. а если я хочу номер скорой помощи добавить?

2019-12-02 16:55 UTC, jzuken commented on Semester_1/Homework_4/Task_4-2/main.c
> +int main()
не вся память очищается

2019-12-10 12:40 UTC, jzuken commented
definitely lost: 8 bytes in 1 blocks

2019-12-17 11:55 UTC, SpirinEgor requested changes
При добавление нового номера не ждёт ввода имени и сразу переходит к вводу номера
```
Please, write down the name:
Please, write down the phone:
```
Из-за этого вся дальнейшая работа неправильная

2019-12-19 21:40 UTC, fefaleksey requested changes
Валгринду очень плохо

2019-12-23 14:59 UTC, SpirinEgor requested changes

2019-12-23 14:59 UTC, SpirinEgor commented on Semester_1/Homework_4/Task_4-2/main.c
> +                return;
Для case так же необходимы {}

2019-12-23 14:59 UTC, SpirinEgor commented on Semester_1/Homework_4/Task_4-2/main.c
> +    while (1)
Здесь должен быть булеан

2019-12-25 11:23 UTC, merged