Задача 4-1
pyaiveoleg/BasicProgramming pull request #19
Opened 2019-10-08 18:11 UTC by pyaiveoleg

2019-10-22 11:06 UTC, jzuken requested changes

2019-10-22 11:06 UTC, jzuken commented on Semester_1/Homework_4/Task_4-1/4-1.c
> +    ListElement* listOfWarriors;
тут хочется видеть работу со структурой List, которая представляет значение этого типа данных. а ListElement — это детали реализации односвязного линейного списка, которые за пределы модуля выносить не стоит

2019-11-23 21:09 UTC, fefaleksey approved these changes
теперь ок

2019-11-24 11:58 UTC, jzuken requested changes

2019-11-24 11:58 UTC, jzuken commented on Semester_1/Homework_4/Task_4-1/main.c
> +    free(listOfWarriors);
проверь, пожалуйста, что у тебя все ячейки списка удаляются (спойлер: нет)

2019-12-01 19:46 UTC, fefaleksey approved these changes
ок

2019-12-02 11:11 UTC, jzuken requested changes

2019-12-02 11:11 UTC, jzuken commented on Semester_1/Homework_4/Task_4-1/CycleList.h
> +    kResult_Fail,
а можно, пожалуйста, не называть таким образом ничего никогда? такие имена рождают кучу вопросов (что за префикс k, почему там camel case и snake case сразу в каком-то диком сочетании и т.п.), и их явно в этом месте быть не должно

2019-12-10 12:16 UTC, SpirinEgor requested changes

2019-12-10 12:16 UTC, SpirinEgor commented on Semester_1/Homework_4/Task_4-1/CycleList.c
> +        return  fail;
Лишний пробел

2019-12-10 12:16 UTC, SpirinEgor commented on Semester_1/Homework_4/Task_4-1/CycleList.c
> +    return  success;
И тут лишний

2019-12-10 12:37 UTC, merged