Task 2 1
pyaiveoleg/BasicProgramming pull request #2
Opened 2019-09-21 16:26 UTC by pyaiveoleg

2019-10-08 11:02 UTC, jzuken requested changes

2019-10-08 11:02 UTC, jzuken commented on main.c
> +#include <stdio.h>
этот файл у тебя лежит в корне репозитория и называется main.c. а что будет, когда ты ещё задач добавишь, они же все вперемешку будут лежать в одном месте, плохо. давай создадим акдеватную структуру каталогов тут и переместим туда этот файл командой git mv

2019-10-08 18:26 UTC, pyaiveoleg commented on main.c
> +#include <stdio.h>
У меня сейчас каждая задача - это ветка из мастер. Так и должно быть? Надо просто переименовать все файлы из main.c в "Номер задачи".с и всё?

2019-10-08 19:34 UTC, pyaiveoleg commented on main.c
> +#include <stdio.h>
И как "Создать структуру каталогов"? Надо в каждой ветке создать папку вида "Homework_2" и перекинуть туда файл вида "2-1.c"?

2019-10-17 12:14 UTC, SpirinEgor requested changes

2019-10-17 12:14 UTC, SpirinEgor commented on .gitignore
> -.idea/*
Не надо удалять этот файл, он же помогает не коммитить лишнего.

2019-10-17 12:14 UTC, SpirinEgor commented on README.md
> -# BasicProgramming
И этот файл тоже трогать не надо. Вообще, данный пр решает определённую задачу, поэтому должны быть затронуты файлы, только которые имеют к ней отношение.

2019-10-17 12:14 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-1/2-1.c
> +void representationOfNumber(int remainingPart, int maximalTerm, int numberOfCurrentTerm, int* currentRepresentation)
Функцию лучше всего называть глаголом

2019-10-17 12:14 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-1/2-1.c
> +        if (maximalTerm > 1) {
Фигурные скобки ставятся с новой строки.

2019-11-18 15:31 UTC, SpirinEgor commented
Я не вижу каких-либо изменений после 17 октября (мои комментарии), хотя в hwproj висит решения от 29 октября. Что-то тут не так.

2019-11-23 13:13 UTC, fefaleksey commented on Semester_1/Homework_2/Task_2-1/main.c
> +{
Лучше int currentRepresentation*, можно не исправлять

2019-11-23 13:13 UTC, fefaleksey commented on Semester_1/Homework_2/Task_2-1/main.c
> +    int currentRepresentation[maxNumber];
Что-то я не вижу никаких ограничений в условии. 
Естественно длинна массива может быть равна 101. И даже (!!!) 102.

2019-11-23 13:13 UTC, fefaleksey commented on Semester_1/Homework_2/Task_2-1/main.c
> +    int currentRepresentation[maxNumber];
Мне кажется, длинна равна значению твоего числа

2019-11-23 22:10 UTC, fefaleksey reviewed
ok

2019-11-24 12:04 UTC, jzuken requested changes

2019-11-24 12:04 UTC, jzuken commented on .gitignore
> -.idea/*
ну тогда я ещё раз скажу: не надо удалять этот файл, он полезный. если я это замерджу, оно же и в мастере удалится

2019-11-24 12:04 UTC, jzuken commented on README.md
> -# BasicProgramming
и этот файл тоже не надо удалять

2019-12-01 19:05 UTC, fefaleksey approved these changes
ok

2019-12-02 11:13 UTC, merged