Задача 5-1
pyaiveoleg/BasicProgramming pull request #21
Opened 2019-10-31 20:31 UTC by pyaiveoleg

2019-11-28 08:59 UTC, SpirinEgor requested changes

2019-11-28 08:59 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_1/main.c
> +bool convertInfixToPostfix(char *inputExpression, Stack* stack, int resultingArray[], int* currentIndexInResultingArray)
Длинная строчка вышла, лучше разбить её на 2

2019-11-28 08:59 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_1/main.c
> +bool convertInfixToPostfix(char *inputExpression, Stack* stack, int resultingArray[], int* currentIndexInResultingArray)
А вообще, стек используется только внутри функции, поэтому логичнее его создавать внутрии неё, а в конце удалять.

2019-11-28 08:59 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_1/main.c
> +bool convertInfixToPostfix(char *inputExpression, Stack* stack, int resultingArray[], int* currentIndexInResultingArray)
Ну и последняя переменная, не надо переусердствовать в название, `resultingArrayLength` будет проще и понятнее

2019-11-28 08:59 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_1/main.c
> +int getcode(char symbol) //код сдвигается, чтобы случайно не совпал с введённым числом
Если введённые числа однозначные, то пересечения точно не будет. Или я не понял для чего эта функция.

2019-11-28 08:59 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_1/main.c
> +    const int maxNumber = 1000;
Эта константа используется в нескольких местах, но при этом всегда объявляется заново. Это не хорошо, так как, например, если понадобится её поменять, то придётся искать все вхождения. Лучше всего один раз в одном месте объявить.

2019-11-28 08:59 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_1/main.c
> +        else if (currentSymbol == ' ') {}
Лучше использовать `continue`

2019-11-28 08:59 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_1/stack.h
> +#ifndef REALISATION_OF_STACK_STACK_H
Лучше просто `STACK_H`

2019-11-30 12:44 UTC, pyaiveoleg commented on Semester_1/Homework_5/Task_1/main.c
> +int getcode(char symbol) //код сдвигается, чтобы случайно не совпал с введённым числом
В какой-то момент кто-то просил сделать поддержку не только однозначных чисел, поэтому совпасть может

2019-11-30 13:03 UTC, pyaiveoleg commented on Semester_1/Homework_5/Task_1/main.c
> +bool convertInfixToPostfix(char *inputExpression, Stack* stack, int resultingArray[], int* currentIndexInResultingArray)
Последняя переменная - это индекс, она становится размером массива только после обработки последнего элемента, а так как индексы есть и в итоговом массиве, и в строчке, лучше оставить как есть, мне кажется

2019-12-10 12:42 UTC, jzuken requested changes

2019-12-10 12:42 UTC, jzuken commented on Semester_1/Homework_5/Task_1/stack.c
> +    return kResult_Ok
:(

2019-12-13 20:49 UTC, fefaleksey requested changes

2019-12-13 20:49 UTC, fefaleksey commented on Semester_1/Homework_5/Task_1/main.c
> +    const int maxInputLength = 1000;
Ну нет, такие предположения делать нельзя

2019-12-13 20:49 UTC, fefaleksey commented on Semester_1/Homework_5/Task_1/main.c
> +    return (int) symbol + maxNumber;
Зачем этот каст? Он сам его сделает (один из операндов инт)

2019-12-13 20:49 UTC, fefaleksey commented on Semester_1/Homework_5/Task_1/main.c
> +    return ((int) symbol >= (int) '0') && ((int) symbol <= (int) '9');
Опять же, лишние касты (и совершенно бесполезные)

2019-12-17 06:03 UTC, fefaleksey requested changes

2019-12-17 06:03 UTC, fefaleksey commented on Semester_1/Homework_5/Task_1/stack.c
> +    if (isStackEmpty(stack))
Рассуждения "не буду тут проверять на NULL, потому что /*название функции*/ это проверит" могут плохо закончиться

2019-12-17 06:03 UTC, fefaleksey commented on Semester_1/Homework_5/Task_1/stack.c
> +    }
А что же она вернет, если stack == NULL?

2019-12-17 06:03 UTC, fefaleksey commented on Semester_1/Homework_5/Task_1/stack.c
> +    stack->first = poppedElement->next;
В твоем случае как раз и закончатся, учитывая, что isStackEmpty вернет непонятно, что

2019-12-17 06:03 UTC, fefaleksey commented on Semester_1/Homework_5/Task_1/stack.c
> +    if (isStackEmpty(stack))
И тут

2019-12-18 10:09 UTC, SpirinEgor commented
Ввёл `(1 + 1) * 2` получил `Error.` и утечку памяти.
Ввёл `(1+1)*2` снова получил `Error.` и утечку памяти.
Так и не понял, что я делают не так(

2019-12-18 10:28 UTC, SpirinEgor commented
Да, теперь работает.
Но вот утечки памяти всё ещё висят

2019-12-19 21:48 UTC, fefaleksey requested changes
Ну сколько можно? Куча утечек

2019-12-19 21:48 UTC, fefaleksey commented on Semester_1/Homework_5/Task_1/main.c
> +                           int* currentIndexInResultingArray, const int shiftForOperators)
100 строк -- это явно перебор

2019-12-23 15:51 UTC, SpirinEgor commented
```
Please, write down the expression (with gaps between numbers and operators):
1 + 1
This is your expression in postfix format:
1 1 + 
```

valgrind:
InvalidRead 3 warnings
InvalidWrite 2 warnings

2019-12-25 09:17 UTC, jzuken requested changes

2019-12-25 09:17 UTC, jzuken commented on Semester_1/Homework_5/Task_1/main.c
> +        return false;
:(

2019-12-25 11:22 UTC, merged