Задача 5-2
pyaiveoleg/BasicProgramming pull request #22
Opened 2019-10-31 20:32 UTC by pyaiveoleg

… стека

2019-11-28 09:10 UTC, SpirinEgor requested changes

2019-11-28 09:10 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/main.c
> +            exit(1);
`exit` является системным вызовом, а не частью языка, поэтому лучше им не пользоваться. Надо до вызова этой функции проверять, что передаётся нужный символ (вроде так и делается у тебя) или бросать исключение, но мы этого не проходили

2019-11-28 09:10 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/main.c
> +void countValueOfWholeExpression(char *inputExpression, StackOfDouble* stack)
Опять же стек можно сделать внутри функции и упростить интерфейс

2019-11-28 09:10 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/main.c
> +void countValueOfWholeExpression(char *inputExpression, StackOfDouble* stack)
Ну и раз функция считает значение выражения, то можно сразу из неё ответ и возвращать.

2019-11-28 09:10 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/main.c
> +        printf("This is the value of your expression:\n%d", (int) value);
Можно вне `if` сделать вывод длиной строки, а потом внутри вывести только число (опять же будет легче потом форматировать).

2019-11-28 09:10 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/stack.c
> +//------------------------StackOfDoubleStack-----------------------------//
Стек стеков?

2019-11-28 09:10 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/stack.c
> +//StackOfInt
Если хочешь комментариями разделять модули, то делай как-то единообразно

2019-11-28 09:10 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/stack.c
> +    return(value);
Для чего тут скобочки?

2019-11-28 09:10 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/stack.c
> +    return(value);
Зачем скобочки?

2019-12-10 12:44 UTC, jzuken commented
definitely lost: 1,000 bytes in 1 blocks

ну алло

2019-12-13 20:56 UTC, fefaleksey requested changes

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/main.c
> +        if (isOperator( (char) currentSymbol))
Но он же и так char

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/main.c
> +            pushToStackOfDouble(binaryOperation(currentSymbol, firstOperand, secondOperand), stack);
Прям просится отдельная функция

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/stack.c
> +    return stck1;
stck1???

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/stack.c
> +}
Угадай, что будет, если я передам NULL?

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/stack.c
> +    stack->head = stackElement;
Ну и тут тоже и ещё много где

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/main.c
> +    }
Зачем?

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/main.c
> +    countValueOfWholeExpression(inputExpression);
Где проверка на корректность

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/main.c
> +    printValueOfWholeExpression(resultingValue);
Функция "count" должна только считать (и все). Печать на экран -- не ее обязанность

2019-12-13 20:56 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/main.c
> +    printValueOfWholeExpression(resultingValue);
Ну и корректность нужно проверять

2019-12-14 18:22 UTC, pyaiveoleg commented on Semester_1/Homework_5/Task_2/main.c
> +    }
Чтобы выводило целое значение, если оно на самом деле целое

2019-12-14 18:33 UTC, pyaiveoleg commented on Semester_1/Homework_5/Task_2/main.c
> +    }
Ладно, уберу это

2019-12-17 05:54 UTC, fefaleksey requested changes

2019-12-17 05:54 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/stack.c
> +    *value = stack->head->value;
А если value == NULL??

2019-12-17 05:54 UTC, fefaleksey commented on Semester_1/Homework_5/Task_2/main.c
> +    char *currentString = (char *) malloc(sizeof(char) * startingSizeOfString);
calloc

2019-12-17 07:10 UTC, pyaiveoleg commented on Semester_1/Homework_5/Task_2/stack.c
> +    *value = stack->head->value;
Value - это переменная double:)

2019-12-17 07:12 UTC, pyaiveoleg commented on Semester_1/Homework_5/Task_2/main.c
> +    char *currentString = (char *) malloc(sizeof(char) * startingSizeOfString);
Что это?)

2019-12-18 10:12 UTC, SpirinEgor commented
Утечки памяти при ошибке

2019-12-19 21:50 UTC, fefaleksey requested changes
УТЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЧКИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИИ

Please, write down the expression:
2 4-5+43934*
Resulting value is 131802.000000

2019-12-23 15:54 UTC, SpirinEgor commented
В случае ошибки по-прежнему утечки
Пример: `1 2`

2019-12-25 11:24 UTC, SpirinEgor requested changes

2019-12-25 11:24 UTC, SpirinEgor commented on Semester_1/Homework_5/Task_2/CountExpressionInPostfix.c
> +    return true;
:(

2019-12-25 11:35 UTC, merged