Решение задачи 7-2
pyaiveoleg/BasicProgramming pull request #27
Opened 2019-11-14 20:55 UTC by pyaiveoleg

2019-11-24 21:32 UTC, fefaleksey requested changes
И во всем коде добавь проверки на входные данные

2019-11-24 21:32 UTC, fefaleksey commented on Semester_1/Homework_7/Task_2/main.c
> +    printf(areStringsEqual(testString, anotherString) ? "These strings are equal" : "These strings are different");
Это что?) тестовый код если и делать, то явно не в main

2019-11-24 21:32 UTC, fefaleksey commented on Semester_1/Homework_7/Task_2/MyString.c
> +}
NULL

2019-11-24 21:32 UTC, fefaleksey commented on Semester_1/Homework_7/Task_2/MyString.c
> +}
NULL

2019-11-24 21:32 UTC, fefaleksey commented on Semester_1/Homework_7/Task_2/MyString.c
> +    string->maxLength *= 2;
Не лучше ли поменять их местами?

2019-11-24 21:32 UTC, fefaleksey commented on Semester_1/Homework_7/Task_2/MyString.c
> +        }
Кажется тут что-то не так:)

2019-11-25 08:08 UTC, jzuken requested changes

2019-11-25 08:08 UTC, jzuken commented on Semester_1/Homework_7/Task_2/main.c
> +    String* extract = getSubstring(anotherString, 2, 4);
ну и память бы почистить было бы неплохо. надо себе футболку сделать с такой надписью

2019-12-08 16:22 UTC, jzuken requested changes

2019-12-08 16:22 UTC, jzuken commented on Semester_1/Homework_7/Task_2/MyString.c
> +        return  kResult_Fail;
пробел лишний

2019-12-08 16:22 UTC, jzuken commented on Semester_1/Homework_7/Task_2/MyString.c
> +    while ((*concatenatedStrings)->maxLength < firstString->length + secondString->length)
вот не нравится мне этот метод чайника. а нельзя сразу выделить памяти столько, сколько надо? ты же знаешь размеры обеих строк

2019-12-08 16:22 UTC, jzuken commented on Semester_1/Homework_7/Task_2/MyString.c
> +        *equalityOfStrings = true;
areEqual

2019-12-08 16:22 UTC, jzuken commented on Semester_1/Homework_7/Task_2/MyString.h
> +    kResult_Ok,
и тоже бы поправить

2019-12-10 12:51 UTC, jzuken requested changes

2019-12-10 12:51 UTC, jzuken commented on Semester_1/Homework_7/Task_2/MyString.c
> +        return  fail;
пробел :)

2019-12-19 12:24 UTC, SpirinEgor commented
Ошибки чтения и записи значений, обращение в не инициализированную память

2019-12-25 11:36 UTC, merged