Задача 7-1
pyaiveoleg/BasicProgramming pull request #31
Opened 2019-11-21 15:44 UTC by pyaiveoleg

2019-12-08 15:58 UTC, jzuken requested changes

2019-12-08 15:58 UTC, jzuken commented on Semester_1/Homework_7/Task_1/AVLtree.h
> +    kResult_Ok,
их лучше именовать как обычные переменные и константы

2019-12-08 15:58 UTC, jzuken commented on Semester_1/Homework_7/Task_1/main.c
> +        else if (strcmp(inputCommand, "Print in Descending Order") == 0)
а давай, пожалуйста, не будем заставлять пользователя вводить войну и мир и придумаем просто цифровые коды для команд

2019-12-08 15:58 UTC, jzuken commented on Semester_1/Homework_7/Task_1/main.c
> +    Tree* set = createTree();
хорошим тоном считается удалять память на том же уровне абстракции, где она и выделялась. а то вот я вижу создание, а удаление где-то в недрах

2019-12-10 12:50 UTC, jzuken commented
запустил, нажал 0 и всё упало. можно я не буду такое проверять?

2019-12-19 12:22 UTC, SpirinEgor commented
Непонятно работает вывод дерева, зачем-то переносы строк, хотя они вроде как не улучшают читаемость...
Так же на пустом дереве просто всё падает, а на каких-то деревьях валгринд начинает ругаться

2019-12-25 11:33 UTC, merged