Task 7 3
pyaiveoleg/BasicProgramming pull request #32
Opened 2019-11-30 11:30 UTC by pyaiveoleg

2019-12-08 16:34 UTC, jzuken requested changes

2019-12-08 16:34 UTC, jzuken commented on Semester_1/Homework_7/Task_3/main.c
> +int main()
definitely lost: 410 bytes in 23 blocks

2019-12-08 16:34 UTC, jzuken commented on Semester_1/Homework_7/Task_3/HashTable.h
> +void addStringToTable(HashTable* hashTable, String* string, int sizeOfHash);
таблица write-only? а поискать там ничего нельзя? удалить?

2019-12-08 16:34 UTC, jzuken commented on Semester_1/Homework_7/Task_3/HashTable.c
> +    bool hasDeleted;
wasDeleted? или просто deleted

2019-12-08 16:34 UTC, jzuken commented on Semester_1/Homework_7/Task_3/HashTable.c
> +    int sizeOfHash;
неоднозначное имя

2019-12-08 16:34 UTC, jzuken commented on Semester_1/Homework_7/Task_3/HashTable.c
> +        hash +=  (int) text[i] * (int) pow(bigPrimaryNumber, i);
а тут переполнений быть не может?

2019-12-08 16:34 UTC, jzuken commented on Semester_1/Homework_7/Task_3/HashTable.c
> +    char* text = (char*) malloc(sizeof(char) * lengthOfString);
я вот думаю, насколько осмысленно каждый раз тут выделять-удалять память? ты же можешь использовать тот указатель, что внутри строки лежит, ты же его только читаешь, не пишешь

2019-12-08 16:34 UTC, jzuken commented on Semester_1/Homework_7/Task_3/HashTable.c
> +        bool equalityOfStrings = false;
плохое имя

2019-12-10 08:52 UTC, pyaiveoleg commented on Semester_1/Homework_7/Task_3/HashTable.c
> +        hash +=  (int) text[i] * (int) pow(bigPrimaryNumber, i);
Переполнение же берет число по модулю "Максимальное число в int"? Я так и задумывал

2019-12-19 12:26 UTC, SpirinEgor commented
Куча утечек, не забудь устранить их так же для случая, когда не получилось открыть файл

2019-12-25 11:20 UTC, fefaleksey commented on Semester_1/Homework_7/Task_3/HashTable.c
> +void delete(HashTable* hashTable, String* key)
А есть какие-то причины того, что этой функции нет в хедере?

2019-12-25 11:22 UTC, merged