Task 8 2
pyaiveoleg/BasicProgramming pull request #34
Opened 2019-12-01 10:50 UTC by pyaiveoleg

2019-12-01 22:43 UTC, fefaleksey requested changes
Разберись с файлами

2019-12-02 16:51 UTC, jzuken requested changes

2019-12-02 16:51 UTC, jzuken commented on Semester_1/Homework_8/Task_2/main.c
> +    int minDistance = INT_MAX;
main.c:24:23: error: use of undeclared identifier 'INT_MAX'
    int minDistance = INT_MAX;
                      ^
main.c:105:26: error: use of undeclared identifier 'INT_MAX'
    const int infinity = INT_MAX;

limits.h надо подключать

2019-12-02 16:57 UTC, pyaiveoleg commented on Semester_1/Homework_8/Task_2/main.c
> +    int minDistance = INT_MAX;
У меня почему-то работало и без этого. Сейчас поправил

2019-12-10 11:14 UTC, SpirinEgor requested changes

2019-12-10 11:14 UTC, SpirinEgor commented on Semester_1/Homework_8/Task_2/main.c
> +        used[currentCapital] = true;
Забыл про 0-индексацию, поэтому валгринд ругается при добавление 7 города

2019-12-10 11:14 UTC, SpirinEgor commented on Semester_1/Homework_8/Task_2/main.c
> +        used[currentCapital] = true;
Ну и собственно такая ошибка тянется везде, запусти валгринд

2019-12-19 12:52 UTC, SpirinEgor commented
Ещё в одном месте ругается на обращение в неициниализированное место в `used`

2019-12-22 05:58 UTC, merged