Task_4-1
pyaiveoleg/BasicProgramming pull request #65
Opened 2020-04-03 18:59 UTC by pyaiveoleg

2020-06-01 23:30 UTC, elena-lyulina requested changes

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/Main.kt
> +        when (readLine()?.toInt() ?: 0) {
Идея все переводить в 0 в случае чего, чтобы программа вывела help -- хорошая, только давай тогда вместо 0 сразу писать CODE_OF_HELP, раз уже это константа. Вдруг ты ее поменяешь потом или забудешь, что за 0 ты тут пишешь.
А еще toInt() бросает ошибку NumberFormatException на пустой строке, например, да и в любом случае, когда не удается перевести в Int. Такие случае надо бы обрабатывать, а не кидать ошибку напрямую пользователю. Например, опять же, выводить help

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/Main.kt
> +        }
Добавь еще, пожалуйста, блок с else на случай, если пользователь ввел какое-то число, не перечисленное до этого. Пока у тебя программа просто никак на такое не реагурует, а, наверное, должна что-то писать для объяснения пользователю, что он делает не то.

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/Main.kt
> +                val inputFile = File("./src/resources/kotlin/homeworks/homework4/task1/testFile.txt")
Ты, кажется, забыл добавить в эту ветку ресурсы, поэтому он сейчас кидает FileNotFoundException. Не надо так :)

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/Main.kt
> +    println("$CODE_OF_IMPORT - import table from file")
Так как у тебя путь к файлу захардкожен, то надо либо писать явно, что таблица будет импортирована из такого-то файла, либо предоставлять пользователю право ввести путь к файлу.

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/Main.kt
> +                    changeHash(readLine()?.toInt() ?: throw IllegalArgumentException("invalid code of hash"))
Если пользователь введет 3, например, то все равно выберется simple hash. Это странно, надо бы в ответ писать, что число неподходящее. Ну и опять же, toInt() бросает NumberFormatException в случае пустой строки и при неудачном касте к инту, так что стоит это обработать дополнительно. А еще не надо бросать в пользователя IllegalArgumentException, надо вывести ему сообщение, что случилось, не прерывя работы программы.

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/Main.kt
> +                print("Choose hash-function: 1 for polynomial hash, 2 for simple hash")
используй println, иначе пользователю на этой же строке придется вводить числа

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/Main.kt
> +                hashTable.changeHash(hashFunction)
Хорошим тоном будет вывести пользователю в конце сообщение, что все ок, хэш поменялся, как ты делаешь, например, с CODE_OF_REMOVE. И добавь это в остальные места, где ничего не выводится в ответ на ввод

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/HashTable.kt
> +        bucket.quantityOfEntries--
а если такой строки в твоей таблице нет?  И лучше будет возвращать Boolean в зависимости от того, удалилась ли данная строка или нет, и выводить пользователю соответствующее сообщение

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/HashTable.kt
> +        if (quantityOfRecords / sizeOfHash > maxLoadFactor) {
У тебя тут деление с округлением, поэтому неточно считается load factor

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/HashTable.kt
> +        println("Load factor is ${quantityOfFilledBuckets.toDouble() / sizeOfHash}")
Ты уж определись, как ты считаешь load factor :) а то в одном месте делишь количество всех записей (на 49й строчке), а тут --- количество заполненных ячеек. А это разные вещи иногда.

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/HashTable.kt
> +        var quantityOfEntries = 0
А зачем ты держишь поле для количества элементов, если ты все равно используешь key.size везде? так ты только тратишь лишние силы на поддержку этого поля в соответствии с длиной key.

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/HashTable.kt
> +    class Record {
В котлине есть такая штука, как [data class ](https://kotlinlang.org/docs/reference/data-classes.html), чтобы создавать классы просто для хранения каких-то данных в их полях. Кажется, что Record как раз тот случай

2020-06-01 23:30 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/HashTable.kt
> +        val valueForExpand = 2
Константы, использующиеся в классе, лучше выносить в поля этого класса и писать, что они const val (как ты делаешь в Main.kt). Заодно узнаешь, что такое companion object, если еще не знаком :)

2020-06-01 23:30 UTC, elena-lyulina commented on src/test/kotlin/homeworks/homework4/task1/HashTableTest.kt
> +        assert(table.search("test1000"))
Немного странно проверять, что только какой-то один тобой выбранный элемент сохранился. Что если все отсальные удалились при перераспределении? В идеале конечно проверить, что сохранились все элементы, но для этого придется ознакомиться, что такое parameterized tests, так как много ассертов в одном тесте -- плохо. Вариант похуже -- просто проверить, что в таблице все еще осталось 2000 элементов (видимо, придется добавить геттеры для соответствующего поля в HashTable)

Ну и это относится ко всем тестам тут, где ты выборочно проверяешь 1 элемент. Лучше все проверять :)

2020-06-01 23:30 UTC, elena-lyulina commented on src/test/kotlin/homeworks/homework4/task1/HashTableTest.kt
> +        assertFalse(table.search("abs"))
Это, если честно, вообще очень странный тест :) Кажется, что рандомная строка 'abs' ну никак не может оказаться в таблице, что ты вообще пытаешься проверить? Надо же какие-то хоть немного реальные случаи проверять

2020-06-01 23:30 UTC, elena-lyulina commented on src/test/kotlin/homeworks/homework4/task1/HashTableTest.kt
> +    }
Не надо в тестах еще раз создавать хэш-функции. Вдруг ты при их создании тут ошибешься и будешь тестировать вообще не те, что используешь в Main? Вдруг со временем функции в Main изменятся, а в тестах останутся прежними, что сделает все тесты бессмысленными?
Используй лучше те, что уже есть в Main, не вижу сильной необходимости их делать private там.

2020-06-01 23:30 UTC, elena-lyulina commented on src/test/kotlin/homeworks/homework4/task1/HashTableTest.kt
> +}
И добавь еще тесты на удаление элементов, пожалуйста

2020-06-05 15:48 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/Main.kt
> +}
Тут Егор за явно ООП, а раз ты еще не исправил ничего, то давайте с интерфейсом для хэш-фцнкций и классами-реализациями :) и все связанные параметры с функциями хранить в соответствующем классе, а не как глобальные переменные. Остальные все прелести такого подхода вам, кажется, написали в чатике

2020-06-08 12:55 UTC, elena-lyulina approved these changes
Исправления зачтены :)

2020-06-08 12:55 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/task1/TableClient.kt
> +            "$CODE_OF_IMPORT - import table from file \"./src/main/resources/homeworks/homework4/task1/testFile.txt\""
Ты этот путь несколько раз используешь, вынеси его в переменную. Выносить все числа/строки/другие вещи в переменные -- прям очень важно, надо это запомнить. Если не уверен, что понимаешь, почему так --- доставай Егора в чатике :)

2020-06-08 13:04 UTC, pyaiveoleg commented on src/main/kotlin/homeworks/homework4/task1/TableClient.kt
> +            "$CODE_OF_IMPORT - import table from file \"./src/main/resources/homeworks/homework4/task1/testFile.txt\""
Поправил

2020-06-08 13:07 UTC, merged