Добавил 1 версию решения задачи 2-3
pyaiveoleg/BasicProgramming pull request #7
Opened 2019-09-24 18:45 UTC by pyaiveoleg

2019-10-08 11:15 UTC, jzuken requested changes

2019-10-08 11:15 UTC, jzuken commented on 2-3.c
> +        printf ("           %dA %dB\n", cows - bulls, bulls);
лучше явно выводить сколько быков, сколько коров. что такое А и В догадываться не хочется

2019-10-08 11:15 UTC, jzuken commented on 2-3.c
> +            if ((guessedNumber[i] == thoughtNumber [0]) || (guessedNumber[i] == thoughtNumber [1])
а зачем тут пробелы перед скобками индексов?

2019-10-17 12:35 UTC, SpirinEgor requested changes

2019-10-17 12:35 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-3/2-3.c
> +    int guessedNumber[4] = {0,0,0,0};
А тут не хватает пробелов.

2019-10-17 12:35 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-3/2-3.c
> +    int thoughtNumber[4] = {rand() % 10, rand() % 10, rand() % 10, rand() % 10};
На википедии указывается, что все цифры числа разные.

2019-10-17 12:35 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-3/2-3.c
> +        guessedNumber[0] = inputNumber;
Это всё делается в цикле.

2019-10-17 12:35 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-3/2-3.c
> +             || (guessedNumber[i] == thoughtNumber[2]) || (guessedNumber[i] == thoughtNumber[3]))
Опять же можно сделать через цикл

2019-11-18 15:40 UTC, SpirinEgor requested changes

2019-11-18 15:40 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-3/main.c
> +    int thoughtNumber[4] = {randomDigit, 0, 0, 0};
Для чего выносить отдельно, можно же сделать так же в цикле, только от 0 до 3

2019-11-18 15:40 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-3/main.c
> +        randomDigit = rand() % 10;
Если сделать do...while цикл, то эту строчку можно убрать, так как генерится будет внутри цикла

2019-11-18 15:40 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-3/main.c
> +            }
В таком случае, все цифры-быки попадут и сюда тоже. Корова -- если цифра есть в обоих числах, НО находится на разных позициях.

2019-11-24 01:02 UTC, fefaleksey commented on Semester_1/Homework_2/Task_2-3/main.c
> +            {
Со скобками ты тут немного перестарался)

2019-11-24 01:02 UTC, fefaleksey commented on Semester_1/Homework_2/Task_2-3/main.c
> +        {
Вот это не поправил

2019-11-24 01:09 UTC, fefaleksey approved these changes
теперь ок

2019-11-24 01:09 UTC, fefaleksey commented on Semester_1/Homework_2/Task_2-3/main.c
> +            if (isDigitUsed[i] && isDigitUsedInGuessedNumber[i] && (!isDigitABull[i]))
(!isDigitABull[i]) тут скобки не нужны

2019-11-24 12:16 UTC, jzuken requested changes

2019-11-24 12:16 UTC, jzuken commented on Semester_1/Homework_2/Task_2-3/main.c
> +void play(int* thoughtNumber, const int quantityOfDigits, const bool* isDigitUsed)
это какая-то чудовищно длинная функция, давай выделим из неё несколько вспомогательных

2019-12-01 19:15 UTC, fefaleksey approved these changes
ok (хотя она все-равно длинновата)

2019-12-02 16:44 UTC, merged