Добавил 1 версию решения задачи 2-4
pyaiveoleg/BasicProgramming pull request #8
Opened 2019-09-24 18:46 UTC by pyaiveoleg

2019-10-08 11:16 UTC, jzuken requested changes

2019-10-08 11:16 UTC, jzuken commented on 2-4.c
> +int compare(const void * x1, const void * x2)   // функция сравнения элементов массива
это как-то слишком сложно. почему бы просто два числа сюда не передать?

2019-10-08 18:15 UTC, pyaiveoleg commented on 2-4.c
> +int compare(const void * x1, const void * x2)   // функция сравнения элементов массива
Для того, чтобы стандартная сортировка работала, ей нужна именно такая функция сравнения

2019-10-17 12:48 UTC, SpirinEgor requested changes

2019-10-17 12:48 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-4/2-4.c
> +    printf("There is maximal repeating element in this array: %d", maxRepeatingElement);
В случае отсутствия такого элемента следует вывести это, а то для теста `0 1 2 3 4` вывод `0`, что неверно.

2019-10-17 12:48 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-4/2-4.c
> +    }
Вообще нет никакой гарантии, что `checkingElement` не станет отрицательным

2019-11-18 16:45 UTC, SpirinEgor requested changes

2019-11-18 16:45 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-4/2-4.c
> +int main() {
Скобочка со следующей строки

2019-11-23 13:17 UTC, fefaleksey commented on Semester_1/Homework_2/Task_2-4/main.c
> +    for (int i = 0; i < maxArraySize; i++)
Я негодую. Зачем тебе память под 1000 элементов? И почему 1000? Память должна выделяться динамически

2019-11-23 22:29 UTC, fefaleksey approved these changes
ок, зачтена

2019-11-24 12:11 UTC, merged