Добавил 1 версию решения задачи 2-5
pyaiveoleg/BasicProgramming pull request #9
Opened 2019-09-24 18:47 UTC by pyaiveoleg

2019-10-08 11:18 UTC, jzuken requested changes

2019-10-08 11:18 UTC, jzuken commented on 2-5.c
> +    }
вот тут одно и то же дважды повтояется, давай лучше вынесем это в функцию

2019-10-17 12:51 UTC, SpirinEgor requested changes

2019-10-17 12:51 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-5/2-5.c
> +        structureOfString[string[i]]++;
Большая часть массива будет пустовать, обычно из `string[i]` вычитают `a`, чтобы получить нумерацию относительно 0.

2019-10-17 12:51 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-5/2-5.c
> +        structureOfString[string[i]]++;
Так же не рекомендуется использовать `string`, как название переменной, так как ассоциируется с типом данным.

2019-11-18 16:47 UTC, SpirinEgor requested changes

2019-11-18 16:47 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-5/2-5.c
> +int main() {
Скобочка не там

2019-11-18 16:47 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-5/2-5.c
> +        structureOfString[stringForAnalyze[i] - (int) 'a']++;
Пробел лишний `(int)'a'`

2019-11-18 16:47 UTC, SpirinEgor commented on Semester_1/Homework_2/Task_2-5/2-5.c
> +    const int quantityOfSymbols = 256;
Раз используются только `a-z` символы, то нет нужды в таком большом массиве

2019-11-23 13:24 UTC, fefaleksey reviewed
Это явно что-то не то

2019-11-24 00:11 UTC, fefaleksey approved these changes
Теперь ок

2019-11-24 12:12 UTC, merged